wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - ./atpropertylistings:/var/www/html/wp-content/plugins/atpropertylistings

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: bad-password-management
